# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.2
    hooks:
    # Run the linter.
    -   id: ruff-check
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: ./.venv/bin/pytest --cov=rstrip --cov-report=html --cov-report=term-missing # Adjust path to your pytest executable if needed
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
